apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-k8s-cicd-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-k8s-cicd-demo
  template:
    metadata:
      labels:
        app: nodejs-k8s-cicd-demo
    spec:
      containers:
        - name: nodejs-k8s-cicd-demo
          image: progod/nodejs-k8s-cicd-demo:TAG
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
